#!/usr/bin/env bash
# configure redirection
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
redir_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "47i\ $redir_page" /etc/nginx/sites-available/default
sudo sed -i "47i\ $redir_page" /etc/nginx/sites-enabled/default
sudo service nginx start
