#!/usr/bin/env bash
# install load balancer 

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
frontend="\nfrontend haproxynode\n\tbind *:80\n\tdefault_backend back_nodes\n"
backend="backend back_nodes\n\tbalance roundrobin\n\tserver 747-web-01 35.243.150.102 check\n\tserver 747-web-02 35.237.124.126 check\n"

echo -e $frontend | sudo tee --append /etc/haproxy/haproxy.cfg
echo -e $backend | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
