#!/usr/bin/env bash
#bad luck 4 8
i=0
while [ $i -lt 10 ]
do
    if (( i==3 ))
    then
	echo "bad luck"
    elif (( i==7 ))
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( i++ ))
done
