#!/usr/bin/env bash
#lot of ifs
file="holbertonschool"
if [ -e "$file" ]
then
    echo "holbertonschool file exists"
    if [ -s "$file" ]
    then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi
    if [ -f "$file" ]
    then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
